### ISSUE TITLE
Keep in sync with upstream

### ISSUE THREAD

**Issue by ianuxfr** [luetzel/bluez#1]
Hi,

Thank you for creating this repo, I finally achieved to make my Shanwan clone work with BT.

Do you plan to maintain this patchset with upcoming Bluez release (5.40 is already out)?

**Comment by luetzel** [comment]
Howdy,
I'm aware that Bluez is going to be updated. I did not create the Shanwan patches. One of the Bluez developers is taking care of them and some day they'll probably make it into the master branch. There are many RetroPie users out there having trouble trying to use sixaxis/sixad and bluetoothd at the same time. Most of them are not experienced enough with Linux to apply the patchset on their own, thus I decided to place a patched version on github.
I'm going to test the patchset on bluez 5.40 soon and will place an update here.

**Comment by luetzel** [comment]
OK, I've created a new branch for bluez-5.40, including the patchset. It compiled without errors on latest Raspbian and I was able to successfully pair two Shanwan controllers at the same time. Let me know if it works for you.

**Comment by ianuxfr** [comment]
> I did not create the Shanwan patches

I know that, I came here from this thread https://retropie.org.uk/forum/topic/42/shanwan-ps3-controller-pi3-retropie-3-6-bluetooth-setup

I assume that the Bluez dev will keep his patchset in sync with the master branch. I was afraid that it will never be merged since the patches are several weeks old already and I've found no evidence of the will to merge on the Bluez mailing list.

I have created a AUR package for Archlinux based on your repo. I will update it to 5.40 when I have time to test it. But shouldn't your master branch be the most recent, and older releases kept in separate ones ? It would be easier for future updgrade.

**Comment by luetzel** [comment]
Thank you for your suggestions. You're right the latest release should go to the master branch - of course. I'll take care of it and change it, as soon as I find some time
I have also observed these patches for quite a while on the bluez mailing list, and I don't understand why they didn't make it, yet, into the master branch.  It is the second-most popular thread in the RetroPie forum and a quite annoying problem for many Shanwan owners ...
